### ISSUE TITLE
NavBar and About section

### ISSUE THREAD

**Issue by RebeccaNovis** [DisgracedM8/DisgracedM8.github.io#1]
- The navbar overlaps with the text in the about section. We would recommend adding a background to the navbar. 

- On smaller screens, the text in the about section cuts off, and you can't see the top of the text, even if you scroll up. 
- The text also overlaps with the photo when shrunk to mobile view
- We would recommend making the font scaleable rather than putting the text in an overflow

- There is text at the bottom beneath the skills that doesn't make sense 

- We recommend removing the copyright symbol since its more of a legal thing

**Comment by JaydenQuallio** [comment]
- Navbar now has a background when scrolled
- Overflow fixed on scroll
- Placeholder text removed for placeholder boxes
- Keeping copyright
